sudo: False

language: python

cache: pip

matrix:
  include:
    - python: 2.7
    - python: 3.3
    - python: 3.4
    - python: 3.5

install:
  # Install dependencies
  - pip install --upgrade setuptools
  - pip install -r requirements.txt
  - python setup.py develop

script:
  - py.test -x -vvv --doctest-modules --pyargs adlfs tests

notifications:
  email: false
