sudo: False

language: python

matrix:
  include:
    - python: 2.7
    - python: 3.3
    - python: 3.4
    - python: 3.5

install:
  # Install dependencies
  - pip install -r requirements.txt
  - python setup.py develop

script:
  - py.test -x --doctest-modules --pyargs tests

notifications:
  email: false
