sudo: false

language: python

cache: pip

matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6

install:
  # Install dependencies
  - pip install -U setuptools pip
  - pip install -r dev_requirements.txt
  - python setup.py develop

  # Install coveralls and pytest coverage
  - pip install coveralls pytest-cov

env:

script:
  - py.test --maxfail=100 -vvv --doctest-modules --cov=azure/datalake/store --pyargs azure.datalake.store tests

after_success:
  - coveralls

notifications:
  email: false

deploy:
  provider: pypi
  user: begoldsm
  skip_upload_docs: true
  # password: use $PYPI_PASSWORD
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: '3.6'
    repo: Azure/azure-data-lake-store-python
